Improved regression script
Added a more complete set of regressions and the ability to not write
to the test device.

diff --git a/regress b/regress
--- a/regress
+++ b/regress
@@ -1,4 +1,27 @@
 #!/bin/bash
+#
+# Copyright 2015 PMC-Sierra, Inc.
+#
+# Licensed under the Apache License, Version 2.0 (the "License"); you
+# may not use this file except in compliance with the License. You may
+# obtain a copy of the License at
+# http://www.apache.org/licenses/LICENSE-2.0 Unless required by
+# applicable law or agreed to in writing, software distributed under the
+# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
+# CONDITIONS OF ANY KIND, either express or implied. See the License for
+# the specific language governing permissions and limitations under the
+# License.
+#
+#
+#   Author: Stephen Bates <stephen.bates@pmcs.com>
+#
+#   Description:
+#     Regression test-suite for the NVM Express CLI.
+#
+
+DEVICE=
+WRITE=false
+LIST=false
 
 RAND_BASE=temp.rand
 RAND_WFILE=${RAND_BASE}.write
@@ -8,6 +31,34 @@ RAND_SIZE=512
 green=$(tput bold)$(tput setaf 2)
 red=$(tput bold)$(tput setaf 1)
 rst=$(tput sgr0)
+
+while getopts ":d:wl" opt; do
+  case $opt in
+    d)
+      DEVICE=${OPTARG}
+      ;;
+    w)
+      echo "WARNING: Write mode enabled, this might trash your drive!"
+      WRITE=true
+      ;;
+    l)
+      LIST=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$DEVICE" ]; then
+     echo "regress: You must specify a NVMe device using -d"
+     exit 1
+fi
 
 function print_pass_fail {
     $* > /dev/null 2>&1
@@ -30,9 +81,27 @@ function run_test {
 make clean > /dev/null || exit -1
 make install > /dev/null || exit -1
 
-run_test dd if=/dev/urandom of=${RAND_WFILE} bs=${RAND_SIZE} count=1
-run_test nvme write /dev/nvme0n1 --start-block=0 --block-count=0 --data-size=${RAND_SIZE} --data ${RAND_WFILE}
-run_test nvme read /dev/nvme0n1 --start-block=0 --block-count=0 --data-size=${RAND_SIZE} --data ${RAND_RFILE}
-run_test diff ${RAND_RFILE} ${RAND_WFILE}
+if $LIST ; then 
+    run_test nvme list
+fi
+run_test nvme id-ctrl ${DEVICE}
+run_test nvme id-ns ${DEVICE}
+run_test nvme list-ns ${DEVICE}
+run_test nvme get-ns-id ${DEVICE}
+run_test nvme get-log ${DEVICE}  --log-id=2 --log-len=512
+run_test nvme fw-log ${DEVICE}
+run_test nvme smart-log ${DEVICE}
+run_test nvme error-log ${DEVICE}
+run_test nvme get-feature ${DEVICE} -f 7
+run_test nvme flush ${DEVICE}
 
-rm ${RAND_RFILE} ${RAND_WFILE} > /dev/null
+if $WRITE ; then
+    run_test dd if=/dev/urandom of=${RAND_WFILE} bs=${RAND_SIZE} count=1
+    run_test nvme write ${DEVICE} --start-block=0 --block-count=0 --data-size=${RAND_SIZE} --data ${RAND_WFILE}
+fi
+run_test nvme read ${DEVICE} --start-block=0 --block-count=0 --data-size=${RAND_SIZE} --data ${RAND_RFILE}
+if $WRITE ; then
+    run_test diff ${RAND_RFILE} ${RAND_WFILE}
+    rm ${RAND_WFILE} > /dev/null
+fi
+rm ${RAND_RFILE} > /dev/null
